apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ml-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /ml
        pathType: Prefix
        backend:
          service:
            name: ml-ml-service
            port:
              number: 80
