replicaCount: 1
image:
  repository: acrhraprod.azurecr.io/ml
  tag: "b7"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
env: []
