apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ml
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wassimchamakh/hr-analytics.git
    targetRevision: HEAD
    path: _gitops_work/helm-charts/ml
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
