# Production values for ML — IMAGE TAG IS UPDATED BY JENKINS CI
image:
  repository: acrhraprod7e7a9fc9.azurecr.io/ml
  tag: "b21"
ingress:
  enabled: true
  host: ""
  tls: false
  path: /ml(/|$)(.*)
  pathType: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
autoscaling:
  enabled: false
