{{- if .Values.secretProvider.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Chart.Name }}-secrets
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    keyvaultName: {{ .Values.secretProvider.keyvaultName }}
    tenantId: {{ .Values.secretProvider.tenantId }}
    objects: |
      array:
        {{- range .Values.secretProvider.secrets }}
        - |
          objectName: {{ .key }}
          objectType: secret
        {{- end }}
{{- end }}
