apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ingress.yaml
  - network-policy.yaml
  - jenkins/rbac.yaml
  - jenkins/pvc.yaml
  - jenkins/service.yaml
  - jenkins/deployment.yaml
  - sonarqube/postgres-secret.yaml
  - sonarqube/pvc.yaml
  - sonarqube/postgres.yaml
  - sonarqube/sonarqube.yaml