apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd
  labels:
    # Allow privileged initContainers (needed by SonarQube for sysctl)
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
