replicaCount: 1

image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

persistence:
  enabled: true
  size: 1Gi
  storageClass: managed-csi
