# Essential configuration only
replicaCount: 2

# Container image
image:
  repository: acrdevopscicd001.azurecr.io/backend
  tag: "latest"
  pullPolicy: Always

# Service configuration
service:
  type: ClusterIP
  port: 80
  targetPort: 5501  # Adjust based on your backend port

# Resource limits
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

# Environment variables for backend
env: []
# Example:
# env:
#   - name: DATABASE_URL
#     value: "mongodb://mongo-service:27017/myapp"
#   - name: JWT_SECRET
#     value: "your-jwt-secret"
#   - name: NODE_ENV
#     value: "production"