replicaCount: 0
image:
  repository: acrhraprod.azurecr.io/backend
  tag: "b8"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
resources:
  limits:
    cpu: 300m
    memory: 384Mi
  requests:
    cpu: 100m
    memory: 128Mi
env:
  - name: NODE_ENV
    value: "production"
  - name: KEYCLOAK_URL
    value: "http://keycloak.default.svc.cluster.local:8080"
  - name: KEYCLOAK_REALM
    value: "hr-analytics"
  - name: KEYCLOAK_CLIENT_ID
    value: "hr-analytics-backend"
  - name: REDIS_HOST
    value: "redis.default.svc.cluster.local"
  - name: REDIS_PORT
    value: "6379"
  - name: OLLAMA_BASE_URL
    value: "http://ollama.default.svc.cluster.local:11434"
  - name: OLLAMA_MODEL
    value: "llama3.2:1b"
  - name: ML_SERVICE_URL
    value: "http://ml-ml.default.svc.cluster.local:8000"
  - name: QLIK_TLS_REJECT_UNAUTHORIZED
    value: "true"
