replicaCount: 1

image:
  repository: ollama/ollama
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 11434

resources:
  requests:
    cpu: 100m
    memory: 2Gi
  limits:
    cpu: 2000m
    memory: 4Gi

model: "llama3.2:1b"

persistence:
  enabled: true
  size: 5Gi
  storageClass: managed-csi

healthCheck:
  path: /api/tags
  initialDelaySeconds: 60
  periodSeconds: 30
